name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: task-classifier
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy Function
        run: |
          gcloud functions deploy append-csvs \
            --project task-classifier \
            --runtime python311 \
            --trigger-http \
            --allow-unauthenticated \
            --entry-point hello_http \
            --source ./function_code
